### ISSUE TITLE
get_entities_tsv() with sample_set failing with Error: Embedded NUL in string

### ISSUE THREAD

**Issue by schaluva** [broadinstitute/fiss#141]
From within a Terra workspace's Jupyter Notebook, to read in the contents of a sample_set into a pandas dataframe, we are attempting to use the following FISS command (in R) but seeing an `Embedded NUL in string` error. 

`set_df <- pd$read_csv(io$StringIO(fc$fiss$fapi$get_entities_tsv(project, workspace, "sample_set", model="flexible")$text), sep='\t')` 

While troubleshooting, when the `sample_set` table is changed to just `sample`, this code runs successfully. 

The theory is that when the `sample_set` is downloaded, it downloads with a zip file containing two individual .tsv. When requesting a file_set entity type you get back a zipped attachment containing 2 files. It looks like FISS is trying to load the zip binary data into a data frame, and throwing this error.

The workaround has been to download the sample_set entity files and then upload the appropriate one to the Terra workspace's google bucket and then read in the Jupyter Notebook environment on Terra.

**Comment by dheiman** [comment]
The FISS api ([`firecloud.api`](https://github.com/broadinstitute/fiss/blob/master/firecloud/api.py), in this case being used as [`firecloud.fiss.fapi`](https://github.com/broadinstitute/fiss/blob/7cb3f1254721907dd339cd5bde616860a56c238f/firecloud/fiss.py#L24), which I'm not sure I understand, not being familiar with the R python wrapper being used) module is a direct wrapper for the FireCloud API (in this case https://api.firecloud.org/#!/Entities/downloadEntitiesTSV). The values returned are what that API returns.

The high level wrapper ([`firecloud.fiss`](https://github.com/broadinstitute/fiss/blob/master/firecloud/fiss.py)) has the command [`entity_tsv`](https://github.com/broadinstitute/fiss/blob/7cb3f1254721907dd339cd5bde616860a56c238f/firecloud/fiss.py#L269) which has the logic to detect if the API returned tsv or an archive, returning the former or downloading the latter.

This API changed around 4 years ago, and the high level wrapper was removed, since as you've noticed, zip files aren't that useful when you're expecting a tsv. I added it back a year ago with the new detection functionality.

A really great fix would be to update the API itself with an option to return a tsv for set entities - that would enable me to add the option to the wrapper.

Otherwise, I can treat this as a high-level wrapper feature request to update `fiss.entity_tsv` with an option to extract the zip file and return the tsv. Because `firecloud.fiss.fapi` by necessity returns exactly what the API returns, only changes to the API itself can be used to modify the returns.

**Comment by dheiman** [comment]
Please also check out [dalmatian](https://github.com/broadinstitute/dalmatian), which may already have a solution.

**Comment by schaluva** [comment]
Dalmatian ended up being a solution.
